### ISSUE TITLE
Package lock for NPM

### ISSUE THREAD

**Issue by Download** [Download/mics#11]
@minecrawler see #4 and #9

**Comment by Download** [comment]
You should explain me how this works sometimes. I guess it locks the versions right?

**Comment by minecrawler** [comment]
It's a NPM@5 feature (probably added in response to yarn). Basically, as a developer, you `npm i .` the dependencies, make the source code work, and then distribute the source with the lock file. Anyone installing the package after that with `npm i mics` will get the exact dependency versions as described in the lock file. That way, the runtime environment will reflect the one which was used by the developer, so the probability of it working is very high. The dependencies can be updated by running `npm update .` or `npm i .` in the package root, the new versions will then be reflected in the lockfile.

For more information, please refer to the [official docs](https://docs.npmjs.com/files/package-locks).

**Comment by Download** [comment]
Great stuff! Thanks for the explanation. 👍
