### ISSUE TITLE
Remove deprecated stuff

### ISSUE THREAD

**Issue by minecrawler** [Download/mics#16]
Things, like `__proto__`, are standardized in the ECMAScript2015 spec as deprecated features. Hence, they should be replaced by the officially approved way. Example:

```js
obj.__proto__.something
// should become
Object.getPrototypeOf(obj).something
```

(refer to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto))

**Comment by Download** [comment]
So simple!  👍 
Should I pick this one up or will you?

**Comment by minecrawler** [comment]
I don't know if `__proto__` was the only thing (I am not at home right now, so I cannot check), but it's the one which is still in my memory. You can go ahead and pick it up, if you feel like doing it :D

**Comment by Download** [comment]
Will pick this up. Also allows me to practice #17 :)

**Comment by Download** [comment]
Fixed! Thanks for reviewing! Open a new one if you find more.
