### ISSUE TITLE
State of the source code

### ISSUE THREAD

**Issue by minecrawler** [Download/mics#4]
At the moment, mics is advertise as

> Intuitive mixins for ES6 classes

However, in its own code, it uses a wild mix of outdated syntax, like `var` and not even available syntax (at least on NodeJS), like `export function`. I think, it would be better to choose one. Personally, I would prefer ES6 as is available on NodeJS LTS (v6 atm), as it has a lot of benefits, especially for static analysis, and gets rid of the dependency on a transpiler for deployment.

Additionally, there is no linting available, and the code seems to not follow any guidelines. E.g. sometimes there are multiple variables declared per `var` statement, sometimes there are multiple consecutive `var` statements. I would suggest using [airbnb's coding guidelines](https://github.com/airbnb/javascript) in order to improve the code quality and consistency.

After #2 is finished, I could run the code through WebStorm code analysis and fix the syntax one way or the other, if desired. It's only a few lines, so not too much trouble, actually :)

**Comment by Download** [comment]
I'm all for it. However the code should continue to work on ES5 platforms. (I see IE11 as the baseline atm). Oh and it should stay small!  👍

**Comment by Download** [comment]
https://github.com/Download/mics/pull/9

**Comment by Download** [comment]
See specific issues for the progress on the state of the source code.
