### ISSUE TITLE
How would I add a mixin to an existing class?

### ISSUE THREAD

**Issue by lastobelus** [Download/mics#45]
ie, defined in a third-party library. Is this possible?

**Comment by minecrawler** [comment]
Taken from the examples in the README:

```
class X {}
var factory = superclass => class Y extends superclass {}
var Y = mix(factory)
var Z = mix(X, Y)
```

So yes, it is possible. In the example, `Z` is a mix between a regular class and a mixin.

**Comment by lastobelus** [comment]
Oh yes, sorry that was pretty obvious.
